### ISSUE TITLE
Invalid XML data, it can not be empty.

### ISSUE THREAD

**Issue by odinuv** [keboola/adwords-extractor#11]
asi bug?

https://keboola.slack.com/archives/C09U3R1J4/p1514246888000055

"errorOutput": "[2017-12-26 00:06:47] adwords-api.WARNING:  unknown (AwApi-PHP, googleads-php-lib\/27.1.0, PHP\/7.1.8, GuzzleHttp\/6.2.1, curl\/7.38.0) \"POST \/api\/adwords\/reportdownload\/v201705 HTTP\/1.1\" Status: 400  [] []\nInvalid XML data, it can not be empty.\n#0 \/code\/vendor\/symfony\/serializer\/Encoder\/ChainDecoder.php(40): Symfony\\Component\\Serializer\\Encoder\\XmlEncoder->decode('', 'xml', Array)\n#1 \/code\/vendor\/symfony\/serializer\/Serializer.php(269): Symfony\\Component\\Serializer\\Encoder\\ChainDecoder->decode('', 'xml', Array)\n#2 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/AdWords\/Reporting\/v201705\/ReportDownloader.php(140): Symfony\\Component\\Serializer\\Serializer->decode('', 'xml')\n#3 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/AdWords\/Reporting\/v201705\/ReportDownloader.php(117): Google\\AdsApi\\AdWords\\Reporting\\v201705\\ReportDownloader->makeReportRequest(Array)\n#4 \/code\/src\/Keboola\/AdWordsExtractor\/Api.php(175): Google\\AdsApi\\AdWords\\Reporting\\v201705\\ReportDownloader->downloadReportWithAwql('SELECT Campaign...', 'CSV')\n#5 \/code\/src\/Keboola\/AdWordsExtractor\/Extractor.php(99): Keboola\\AdWordsExtractor\\Api->getReport('SELECT Campaign...', '19700101', '20171225', '\/data\/out\/table...')\n#6 \/code\/src\/Keboola\/AdWordsExtractor\/RunCommand.php(51): Keboola\\AdWordsExtractor\\Extractor->extract(Array, '19700101', '20171225')\n#7 \/code\/vendor\/symfony\/console\/Command\/Command.php(264): Keboola\\AdWordsExtractor\\RunCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 \/code\/vendor\/symfony\/console\/Application.php(869): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 \/code\/vendor\/symfony\/console\/Application.php(223): Symfony\\Component\\Console\\Application->doRunCommand(Object(Keboola\\AdWordsExtractor\\RunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/code\/vendor\/symfony\/console\/Application.php(130): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/code\/src\/app.php(17): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 {main}"
}

**Comment by odinuv** [comment]
vcora znovu https://papertrailapp.com/groups/170211/events?selected=887265356132003851&focus=887265356132003851

**Comment by odinuv** [comment]
"output": "Extraction of data for customer Deprecated (1\/13) started\nExtraction of data for customer Deprecated (2\/13) started\nExtraction of data for customer Youtube - ID - TO BE DELETED (3\/13) started\nExtraction of data for customer Youtube ID (4\/13) started\nExtraction of data for customer Youtube - MY (5\/13) started\nExtraction of data for customer Youtube - PH (6\/13) started\nExtraction of data for customer Deprecated (7\/13) started\nExtraction of data for customer Youtube ID - SQA (8\/13) started\nExtraction of data for customer Youtube - PH (9\/13) started\nExtraction of data for customer Youtube - PH (10\/13) started\nExtraction of data for customer Youtube - VN (11\/13) started\nExtraction of data for customer Deprecated (12\/13) started\nExtraction of data for customer Youtube - TH (13\/13) started",
    "errorOutput": "[2018-06-09 00:08:47] adwords-api.WARNING:  unknown (AwApi-PHP, googleads-php-lib\/34.0.0, PHP\/7.1.15, GuzzleHttp\/6.3.2, curl\/7.38.0) \"POST \/api\/adwords\/reportdownload\/v201802 HTTP\/1.1\" Status: 400  [] []\nInvalid XML data, it can not be empty.\n#0 \/code\/vendor\/symfony\/serializer\/Encoder\/ChainDecoder.php(40): Symfony\\Component\\Serializer\\Encoder\\XmlEncoder->decode('', 'xml', Array)\n#1 \/code\/vendor\/symfony\/serializer\/Serializer.php(280): Symfony\\Component\\Serializer\\Encoder\\ChainDecoder->decode('', 'xml', Array)\n#2 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/AdWords\/Reporting\/v201802\/ReportDownloader.php(184): Symfony\\Component\\Serializer\\Serializer->decode('', 'xml')\n#3 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/AdWords\/Reporting\/v201802\/ReportDownloader.php(148): Google\\AdsApi\\AdWords\\Reporting\\v201802\\ReportDownloader->makeReportRequest(Array)\n#4 \/code\/src\/Keboola\/AdWordsExtractor\/Api.php(175): Google\\AdsApi\\AdWords\\Reporting\\v201802\\ReportDownloader->downloadReportWithAwql('SELECT Amount,B...', 'CSV')\n#5 \/code\/src\/Keboola\/AdWordsExtractor\/Extractor.php(99): Keboola\\AdWordsExtractor\\Api->getReport('SELECT Amount,B...', '20180606', '20180608', '\/data\/out\/table...')\n#6 \/code\/src\/Keboola\/AdWordsExtractor\/RunCommand.php(51): Keboola\\AdWordsExtractor\\Extractor->extract(Array, '20180606', '20180608')\n#7 \/code\/vendor\/symfony\/console\/Command\/Command.php(252): Keboola\\AdWordsExtractor\\RunCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 \/code\/vendor\/symfony\/console\/Application.php(946): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 \/code\/vendor\/symfony\/console\/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Keboola\\AdWordsExtractor\\RunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/code\/vendor\/symfony\/console\/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/code\/src\/app.php(17): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#12 {main}",
    "

https://keboola.slack.com/archives/C09U3R1J4/p1528502946000049

**Comment by JakubMatejka** [comment]
Fixed by https://github.com/keboola/adwords-extractor/releases/tag/5.1.1
