### ISSUE TITLE
Retry

### ISSUE THREAD

**Issue by odinuv** [keboola/adwords-extractor#12]
Application error: 147946154733.dkr.ecr.us-east-1.amazonaws.com/developer-portal-v2/keboola.ex-google-analytics-v4:2.2.6 container '367472981-367472967.367472983--0-keboola-ex-google-analytics-v4' failed: (2) [2018-03-16 00:27:45] ex-google-analytics.ERROR: <!DOCTYPE html> <html lang=en> <meta charset=utf-8> <meta name=viewport ... temporary error and could not complete your request.<p>Please try again in 30 seconds. <ins>That’s all we know.</ins> [] []

**Comment by odinuv** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1521159486000139

**Comment by JakubMatejka** [comment]
Fixed by https://github.com/keboola/adwords-extractor/releases/tag/5.1.1
