### ISSUE TITLE
SOAP-ERROR: Parsing WSDL: Couldn't load from...

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/adwords-extractor#15]
docker-ad5b99a8b28cdd1f6c3d7bdfb63ffddb

```
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/mcm/v201710/ManagedCustomerService?wsdl' : Start tag expected, '<' not found

#0 /code/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(75): SoapClient->SoapClient('https://adwords...', Array)
#1 /code/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201710/mcm/ManagedCustomerService.php(91): Google\AdsApi\Common\AdsSoapClient->__construct('https://adwords...', Array)
#2 [internal function]: Google\AdsApi\AdWords\v201710\mcm\ManagedCustomerService->__construct(Array)
#3 /code/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(39): ReflectionClass->newInstanceArgs(Array)
#4 /code/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClientFactory.php(87): Google\AdsApi\Common\Util\Reflection->createInstance('Google\\AdsApi\\A...', Array)
#5 /code/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsServices.php(55): Google\AdsApi\Common\AdsSoapClientFactory->generateSoapClient(Object(Google\AdsApi\AdWords\AdWordsSession), Object(Google\AdsApi\AdWords\AdWordsHeaderHandler), Object(Google\AdsApi\AdWords\AdWordsServiceDescriptor))
#6 /code/src/Keboola/AdWordsExtractor/Api.php(138): Google\AdsApi\AdWords\AdWordsServices->get(Object(Google\AdsApi\AdWords\AdWordsSession), 'Google\\AdsApi\\A...')
#7 /code/src/Keboola/AdWordsExtractor/Extractor.php(78): Keboola\AdWordsExtractor\Api->getCustomersYielded('20180101', '20180804')
#8 /code/src/Keboola/AdWordsExtractor/RunCommand.php(51): Keboola\AdWordsExtractor\Extractor->extract(Array, '20180101', '20180804')
#9 /code/vendor/symfony/console/Command/Command.php(240): Keboola\AdWordsExtractor\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /code/vendor/symfony/console/Application.php(858): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /code/vendor/symfony/console/Application.php(216): Symfony\Component\Console\Application->doRunCommand(Object(Keboola\AdWordsExtractor\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /code/vendor/symfony/console/Application.php(122): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /code/src/app.php(17): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}
```

https://connection.keboola.com/admin/utils/logs?file=2018/08/06/02/2018-08-06-02-01-25-5b678fd52cb3e-exception
https://connection.keboola.com/admin/utils/logs?file=2018/08/06/02/2018-08-06-02-01-25-5b678fd531f36-log

**Comment by ErikZigo** [comment]
Neni to deprecovana verze api? To WSDL na webu neni a jelikoz je to verze 2017 tak bych tomu i veril.

**Comment by ondrejhlavacek** [comment]
Děje se to i na `keboola.ex-google-adwords-v201710`. Tak by to asi mohlo skončit jako user error, ať se použije jiná komponenta? (`keboola.ex-google-adwords-reports-v201802`?)

**Comment by ErikZigo** [comment]
https://developers.google.com/adwords/api/docs/sunset-dates

**Comment by ErikZigo** [comment]
![image](https://user-images.githubusercontent.com/1726727/43712800-b50f0e6e-9977-11e8-80fd-78678d822f66.png)

**Comment by ErikZigo** [comment]
Ta komponenta je oznacena jako deprecated a je tam i migrace na novy extractor. Tak myslim ze to staci?

Akorat se mi nedari na statusu najit, ze bysme oznamili ze ten stary je deprecated.

Jinak google pri nacitani toho wsdl vraci HTTP 200 a textovou odpoved `WSDL not found for https://adwords.google.com/api/adwords/mcm/v201710/ManagedCustomerService?wsdl` 👎

**Comment by ErikZigo** [comment]
Pripadne muzu napsat vsem co pouzivaj tu starou verzi at si to zmigrujou

**Comment by ondrejhlavacek** [comment]
A co kdyby to jen nekončilo app errorem, ale user errorem s informací o migraci? Tohle imho app error  bejt nemá.

**Comment by ErikZigo** [comment]
Ten extractor v201710 je od listopadu deprecated. Bezi na 4.x tohodle extractoru. Aktulani extractor bezi na 5.x

Jelikoz appky jedou z tohodle repa, udelal bych to asi takhle:

Ze starsich verzi bych udelal samostatne branche a tam natvrdo do kodu dal UserException s infem o migraci. Tagnul bych to jako 4.x.y a rucne deploynul do ECR.

**Comment by ondrejhlavacek** [comment]
Měl bys na to čas, nebo najdemě někoho jinýho?

**Comment by ErikZigo** [comment]
Jakub ma dovolenou. tak ja to klidne udelam az budu mit chvili volna.

Jen jsem si chtel ujasnit myslenku :-)

**Comment by ondrejhlavacek** [comment]
Tak jestli máš volno na zendesku... :-)

Tu user exception bys dal rovnou na začátek, aby to vyfailovalo hned?

**Comment by ErikZigo** [comment]
No ted nemam, ale treba v dalsich dnech bude. Jo pro ty stary verze bych to udelal ze hned. Do zadnych vetsich akci bych se asi nepoustel.

**Comment by ErikZigo** [comment]
https://github.com/keboola/adwords-extractor/tree/v201710

- Doplnil jsem vyhozeni vyjimky
- Vyhodil stavajici testy
- Dodal test na exit status a error message
- Zrusil pro tuhle branch deploy na travisu
- Deploynul rucne do ECR




![image](https://user-images.githubusercontent.com/1726727/44148067-fec1b1d0-a096-11e8-8dc7-3d6ba5ec6afd.png)

**Comment by ondrejhlavacek** [comment]
@ErikZigo Řekl bych, že tam asi má bejt "Please migrate to **a** newer version".

**Comment by ErikZigo** [comment]
Done

**Comment by ErikZigo** [comment]
Sakra jeste bezi i extractory na predminule verzi extractoru v 3.x. Api Googlu v201705.

Jdu to taky uparvit

**Comment by ErikZigo** [comment]
![image](https://user-images.githubusercontent.com/1726727/44199359-28d9a380-a144-11e8-878f-2b1863165075.png)

Done
