### ISSUE TITLE
invalid_grant

### ISSUE THREAD

**Issue by yustme** [keboola/adwords-extractor#22]
### Problém
Na jednom projektu byl extractor zaregistrovaný skrze OAuth a týpka s tím e-mailem nejspíš vyhodili a autorizace přestala fungovat a vrací InternalError:
https://keboola.slack.com/archives/C09U3R1J4/p1551754926009700
```
https://oauth2.googleapis.com/token` resulted in a `400 Bad Request` response:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

### Řešení
Pokud se nepovede lognout, tak by se měla vracet user error a né internal error.

**Comment by pivnicek** [comment]
dalsi: https://keboola.slack.com/archives/C09U3R1J4/p1552532529024400

**Comment by ondrejhlavacek** [comment]
další https://keboola.slack.com/archives/C09U3R1J4/p1552878066004200
