### ISSUE TITLE
server unavailable

### ISSUE THREAD

**Issue by odinuv** [keboola/adwords-extractor#24]
https://keboola.slack.com/archives/C09U3R1J4/p1557828074127500
https://keboola.slack.com/archives/C09U3R1J4/p1557828074127500

 failed: (2) Server error: `POST https:\/\/oauth2.googleapis.com\/token` resulted in a `503 Service Unavailable` response:\n{\n  \"error\": {\n    \"code\": 503,\n    \"message\": \"The service is currently unavailable.\",\n    \"status\": \"UNAVAILABLE\"\n  }\n (truncated...)\n\n#0 \/code\/vendor\/guzzlehttp\/guzzle\/src\/Middleware.php(66): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))\n#1 \/code\/vendor\/guzzlehttp\/promises\/src\/Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))\n#2 \/code\/vendor\/guzzlehttp\/promises\/src\/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(GuzzleHttp\\Psr7\\Response), Array)\n#3 \/code\/vendor\/guzzlehttp\/promises\/src\/TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()\n#4 \/code\/vendor\/guzzlehttp\/promises\/src\/Promise.php(246): GuzzleHttp\\Promise\\TaskQueue->run(true)\n#5 \/code\/vendor\/guzzlehttp\/promises\/src\/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()\n#6 \/code\/vendor\/guzzlehttp\/promises\/src\/Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#7 \/code\/vendor\/guzzlehttp\/promises\/src\/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()\n#8 \/code\/vendor\/guzzlehttp\/promises\/src\/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()\n#9 \/code\/vendor\/guzzlehttp\/guzzle\/src\/Client.php(106): GuzzleHttp\\Promise\\Promise->wait()\n#10 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/Common\/AdsGuzzleProxyHttpHandler.php(63): GuzzleHttp\\Client->send(Object(GuzzleHttp\\Psr7\\Request), Array)\n#11 \/code\/vendor\/google\/auth\/src\/OAuth2.php(501): Google\\AdsApi\\Common\\AdsGuzzleProxyHttpHandler->__invoke(Object(GuzzleHttp\\Psr7\\Request))\n#12 \/code\/vendor\/google\/auth\/src\/Credentials\/UserRefreshCredentials.php(113): Google\\Auth\\OAuth2->fetchAuthToken(Object(Google\\AdsApi\\Common\\AdsGuzzleProxyHttpHandler))\n#13 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/Common\/Util\/OAuth2TokenRefresher.php(66): Google\\Auth ... zleProxyHttpHandler))\n#15 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/Common\/AdsSoapClient.php(114): Google\\AdsApi\\AdWords\\AdWordsHeaderHandler->generateHttpHeaders(Object(Google\\AdsApi\\AdWords\\AdWordsSession))\n#16 \/code\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/AdWords\/v201809\/mcm\/ManagedCustomerService.php(103): Google\\AdsApi\\Common\\AdsSoapClient->__soapCall('get', Array)\n#17 \/code\/src\/Keboola\/AdWordsExtractor\/Api.php(120): Google\\AdsApi\\AdWords\\v201809\\mcm\\ManagedCustomerService->get(Object(Google\\AdsApi\\AdWords\\v201809\\cm\\Selector))\n#18 \/code\/src\/Keboola\/AdWordsExtractor\/Extractor.php(94): Keboola\\AdWordsExtractor\\Api->getAllYielded(Object(Google\\AdsApi\\AdWords\\v201809\\mcm\\ManagedCustomerService), Object(Google\\AdsApi\\AdWords\\v201809\\cm\\Selector), 500)\n#19 \/code\/src\/Keboola\/AdWordsExtractor\/RunCommand.php(51): Keboola\\AdWordsExtractor\\Extractor->extract(Array, '20150101', '20191231')\n#20 \/code\/vendor\/symfony\/console\/Command\/Command.php(255): Keboola\\AdWordsExtractor\\RunCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#21 \/code\/vendor\/symfony\/console\/Application.php(953): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#22 \/code\/vendor\/symfony\/console\/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Keboola\\AdWordsExtractor\\RunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#23 \/code\/vendor\/symfony\/console\/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#24 \/code\/src\/app.php(17): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput),

**Comment by ondrejhlavacek** [comment]
zas https://keboola.slack.com/archives/C09U3R1J4/p1560567771002300

**Comment by tomasfejfar** [comment]
Tohle by mohla být jednoduchá issue pro @ondrajodas nebo @fejjo

**Comment by fejjo** [comment]
Pozriem sa na to.
