### ISSUE TITLE
`400 Bad Request` response: {"error":"invalid_grant","error_description":"Bad Request"}

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/adwords-extractor#29]
Končí to app errorem, měl by to bejt spíš user error

https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/12/03/01/2019-12-03-01-03-14-5de5a64211e89-exception
https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/12/03/01/2019-12-03-01-03-14-5de5a642207ed-log

**Comment by tomasfejfar** [comment]
Should have been fixed by https://github.com/keboola/adwords-extractor/pull/23

**Comment by tomasfejfar** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1579565081008800

**Comment by tomasfejfar** [comment]
cc @ondrajodas

**Comment by tomasfejfar** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1579600593001800

**Comment by ondrajodas** [comment]
založil jsem na to issue
https://keboola.atlassian.net/browse/COM-117

tak to tady zavřu
