### ISSUE TITLE
Dokumentace je chybna

### ISSUE THREAD

**Issue by vokurka** [keboola/adwords-extractor#3]
Ahoj,

na README tady na GitHubu jsem se dostal proklikem primo z KBC UI (coz predpokladam udela dost lidi), zkopiroval si ukazkovou konfiguraci z readme a nasadil ji. Bohuzel nefungovala, protoze je nejspis zastarala nebo z blbeho mista. Pomoci screenu z posthaven jsem zrekonstruoval jak by mela teda vypadat, tady je seznam veci, kterych jsem si vsiml:

1) na githubu je uvedena konfigurace i s casti oauth a parameters, zatimco toto neni vubec zpristupneno - je to dost zavadejici :(

2) na githubu je navic lehce prehlednutelna dvojtecka u "customer_id:" : "..." - pokud udelam copy paste, jsem v pasti :)

3) na githubu je pole dotazu jako "reports", spravne funguje ale "queries"

4) nevim kdo nebo co to dela, ale dojde k prejmenovani sloupcu z AWQL query, takze pak na me vyskoci hlaska "Cannot upload file 'in.c-ex-adwords.report-campaign_performance.csv' to table 'in.c-ex-adwords.campaign_performance' in Storage API: Primary key columns "CampaignId,Date" not found in "Campaign_ID,Day,Avg_CPC,Avg_CPM,Avg_position,Clicks,Cost,Impressions,Network" --> pritom v konfiguraci mam stejne jmeno sloupce jak v query, tak v primary objektu.

Pokud jeste na neco prijdu, dam vedet :)

**Comment by JakubMatejka** [comment]
Ahoj, a jéje, moc se omlouvám. ;o/ Opravil jsem ty překlepy v Readme (2 a 3) a doplnil status aby to bylo jasnější (1). Co se ale týče názvů sloupců (4), tak to bohužel dělá přímo AdWords, že je ve výsledným csv pojmenuje úplně jinak než jsou v AWQL. Podívám se jestli se s tím nedá něco udělat, ale trochu se obávám že ne.

**Comment by JakubMatejka** [comment]
Tak už jsem to našel. Názvy sloupců v csv se dají najít v dokumentaci reportů: https://developers.google.com/adwords/api/docs/appendix/reports pod "Display Name" (přičemž mezery je třeba nahradit podtržítkama). Viz. obr.

<img width="1123" alt="campaign_performance_report_ _ _adwords_api_ _ _google_developers" src="https://cloud.githubusercontent.com/assets/215660/13423602/2366fb3a-df9c-11e5-8b0b-f04df8f8564b.png">

**Comment by padak** [comment]
to by stálo za to nalinkovat do UI nebo prozatím aspoň do apiary, co?

**Comment by vokurka** [comment]
Btw: Pokud si predstavim, ze jsem se prave dostal k nove konfiguraci adwords ex v2, kliknu si na dokumentaci, dostanu se na github a copy pastnu example. Ten ale obsahuje navic objekt "parameters", takze budu dostavat v jednom kuse chybu "Missing parameter "developer_token"" a nebudu si s tim vedet rady :/ (true story :) )

Nehodil by se tedy nejaky priklad v readme, ktery primo bude fungovat v ex?

**Comment by JakubMatejka** [comment]
Problém je asi v tom, že tohle je spíš programátorská dokumentace, kdežto ui tě od části toho odstíní. Tady to upravit jak píšeš nemůžu, protože to pak nebude fungovat bez použití v ui. Tak nevím, asi by to chtělo nějakou dokumentaci přímo pro ui ještě někde jinde?

**Comment by JakubMatejka** [comment]
Apiary asi ne, protože to už žádný API nemá

**Comment by vokurka** [comment]
Naprosto chapu programatorskou dokumentaci, jen uvazuju jako X klientu, kteri se na ni dostanou primo z UI, kdyz budou cely brezen migrovat stary adwords ex na novy :)

**Comment by JakubMatejka** [comment]
Jasně, rozumím. Já teď přemýšlím kam to napsat. Myslel jsem že to bude jasný z toho screenshotu, ale mělo mě napadnout že to nebude stačit ;o)

**Comment by Halama** [comment]
@JakubMatejka dal bych to zatim jako nejaky markdown k tomu repozitari a na to nasmeroval ten link z ui. Ten clovek by tam pak mel jenom udelat copy paste nez to bude samoobsluzne z ui.

**Comment by JakubMatejka** [comment]
Tak jo, napsal jsem to na novou stránku a status nalinkoval na ni:
https://github.com/keboola/adwords-extractor/wiki/Configuration-in-KBC-UI
