### ISSUE TITLE
read oauth client_id and secret from oauth bundle data

### ISSUE THREAD

**Issue by Halama** [keboola/adwords-extractor#4]
client_id and secret is provided by oauth bundle so it is not necessary to put it into `image_parametrs` anymore.

https://github.com/keboola/gmail-extractor/commit/ade011c75126045f23beb52ec6a54926287b7bb8

**Comment by JakubMatejka** [comment]
fixed by 7f7f06731644f770e1f4812ebaaa53970ace3911
