### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by vokurka** [keboola/adwords-extractor#5]
Hi guys,

sorry for bringing this up, it is really a cosmetic thing. Still, took me and a client a while to debug.

When the refresh token is no longer valid, the extractor (or oauth2 component?) gives me this error message:

"Authorization Error, your refresh token is probably not valid. Try to generate new one."

It would be good if there was something like "Check if you have still access to the service" or similar, as this did not crossed my mind immediately...

Like I said, really small thing, but would improve user experience :)

Thanks and have a great weekend!

**Comment by JakubMatejka** [comment]
Fixed by a0c0bd401139eb15e31e08432c945b31615f6708
