### ISSUE TITLE
Encrypt token

### ISSUE THREAD

**Issue by padak** [keboola/adwords-extractor#7]
It would be great if Google Developer Token will be encrypted by default.

**Comment by padak** [comment]
(originally reported by Sun Marketing - https://keboola.zendesk.com/agent/tickets/5382)

**Comment by JakubMatejka** [comment]
Extraktor enkryptovaný developer token podporuje od začátku (https://github.com/keboola/adwords-extractor/blob/master/src/run.php#L33). Problém je, že někdo, tuším že odin, nasetupoval do uička konfigurační schéma bez enkrypce a jestli jsem to dobře pochopil, tak to nejde snadno přehodit, protože by se tím vymazaly konfigurace klientů, kteří enkrypci nepoužívají.

**Comment by padak** [comment]
Při procházení Productboardu jsem na to narazil znovu (https://keboola.productboard.com/feature-board/22395-strategic/features/343588) - pokud to nejde opravit, můžeme vydat novou verzi a tu starou deprekovat?

**Comment by JakubMatejka** [comment]
To už je vyřešený
